name: master_drift_provider
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  drift: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.0.0
  path: ^1.8.2

  permission_handler: ^10.2.0
  spreadsheet_decoder: ^2.1.1
  intl: ^0.17.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  drift_dev: ^2.3.3
  build_runner: ^2.3.2

flutter:

  uses-material-design: true

